### PR TITLE
Add message-tags to cap req so we get message ids from server

### PR DESCRIPTION
**Pull request by 790**

### CODE REVIEW

**Comment by prawnsalad** [comment]
The time in row.ts is the time the message was received or its time tag already https://github.com/kiwiirc/kiwibnc/blob/65e6bd097291a6d50f15e2f2acff512b02723927/src/worker/messagestores/sqlite.js#L73

**Comment by prawnsalad** [comment]
Ah actually, I see it's not using the time from the tags here, https://github.com/kiwiirc/kiwibnc/blob/65e6bd097291a6d50f15e2f2acff512b02723927/src/worker/messagestores/sqlite.js#L96

**Comment by prawnsalad** [comment]
Any update on this?

**Comment by 790** [comment]
The changes are covered by the echo message PR, so this isn't needed anymore

**Pull request closed without merging**
